export const LOCAL_STORAGE_TOKEN_NAME = "auth-token";

export const OWNPROJECTS_LOADED_SUCCESS = "OWNPROJECTS_LOADED_SUCCESS";
export const OWNPROJECTS_LOADED_FAIL = "OWNPROJECTS_LOADED_FAIL";
export const GUESSPROJECTS_LOADED_SUCCESS = "GUESSPROJECTS_LOADED_SUCCESS";
export const GUESSPROJECTS_LOADED_FAIL = "GUESSPROJECTS_LOADED_FAIL";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const FIND_PROJECT_SUCCESS = "FIND_PROJECT_SUCCESS";
export const FIND_PROJECT_FAIL = "FIND_PROJECT_FAIL";
export const UPDATE_MEMBERS = "UPDATE_MEMBERS";

export const TASKS_LOADED_SUCCESS = "TASKS_LOADED_SUCCESS";
export const TASKS_LOADED_FAIL = "TASKS_LOADED_FAIL";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const FIND_TASK = "FIND_TASK";

export const COMMENTS_LOADED_SUCCESS = "COMMENTS_LOADED_SUCCESS";
export const COMMENTS_LOADED_FAIL = "COMMENTS_LOADED_FAIL";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
